/*
  Auto-generated by Spline
*/

"use client"

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'
import { Suspense, useEffect, useState } from 'react'

// Componente de la escena Spline original
function Scene({ scrollY = 0, heroHeight = 0 }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/tl3xShxRq-DfK6sh/scene.splinecode')
  
  if (!nodes || !materials) {
    return null;
  }
  
  return (
    <>
      <color attach="background" args={['#573372']} />
      <group dispose={null}>
        <scene name="Scene">
          <group
            name="Nightly Logo"
            position={[79.49, -424.55, 4.52]}
            rotation={[-Math.PI / 2, -0.65, -Math.PI]}
            scale={0.5}
          >
            <mesh
              name="Path"
              geometry={nodes.Path.geometry}
              material={materials['Nightly uppath']}
              castShadow
              receiveShadow
              position={[-467.09, -4, 1022.34]}
              rotation={[-Math.PI / 2, 0, -1.66]}
              scale={2}
            />
            <mesh
              name="Path 2"
              geometry={nodes['Path 2'].geometry}
              material={materials['Nightly downpath']}
              castShadow
              receiveShadow
              position={[-747.54, -22, 529.95]}
              rotation={[-Math.PI / 2, 0, 1.36]}
              scale={2}
            />
          </group>
          <mesh
            name="Dust Small"
            geometry={nodes['Dust Small'].geometry}
            material={materials['Dust Small Material']}
            visible={false}
            castShadow
            receiveShadow
            position={[0, 0, 298.57]}
          />
          <mesh
            name="Dust Big"
            geometry={nodes['Dust Big'].geometry}
            material={materials['Dust Big Material']}
            visible={false}
            castShadow
            receiveShadow
          />
          <group name="SOLIDS" position={[-70.11, -616.77, -3.08]}>
            <mesh
              name="Cylinder 11"
              geometry={nodes['Cylinder 11'].geometry}
              material={materials.Solids}
              castShadow
              receiveShadow
              position={[-750.88, -70.18, -541.96]}
              scale={1.46}
            />
            <mesh
              name="Cylinder 10"
              geometry={nodes['Cylinder 10'].geometry}
              material={materials.Solids}
              castShadow
              receiveShadow
              position={[501.77, 116.79, -541.96]}
              scale={0.63}
            />
            <mesh
              name="Cylinder 9"
              geometry={nodes['Cylinder 9'].geometry}
              material={materials.Solids}
              castShadow
              receiveShadow
              position={[288.17, -33.71, -784.94]}
              scale={1.42}
            />
            <mesh
              name="Cylinder 8"
              geometry={nodes['Cylinder 8'].geometry}
              material={materials.Solids}
              castShadow
              receiveShadow
              position={[-190.67, 68.23, -376.96]}
            />
            <mesh
              name="Cylinder 5"
              geometry={nodes['Cylinder 5'].geometry}
              material={materials.Solids}
              castShadow
              receiveShadow
              position={[-436.63, -24.25, 818.78]}
            />
            <mesh
              name="Cylinder 4"
              geometry={nodes['Cylinder 4'].geometry}
              material={materials.Solids}
              castShadow
              receiveShadow
              position={[-925.98, 68.24, 166.41]}
            />
            <mesh
              name="Cylinder 3"
              geometry={nodes['Cylinder 3'].geometry}
              material={materials.Solids}
              castShadow
              receiveShadow
              position={[-648.84, 29.78, 555.99]}
            />
            <mesh
              name="Cylinder 2"
              geometry={nodes['Cylinder 2'].geometry}
              material={materials.Solids}
              castShadow
              receiveShadow
              position={[647.89, 117.45, 664.51]}
            />
            <mesh
              name="Cylinder 7"
              geometry={nodes['Cylinder 7'].geometry}
              material={materials.Solids}
              castShadow
              receiveShadow
              position={[-1191.98, -68.83, 464.8]}
            />
            <mesh
              name="Cylinder 6"
              geometry={nodes['Cylinder 6'].geometry}
              material={materials.Solids}
              castShadow
              receiveShadow
              position={[1171.98, 72, -153.21]}
            />
            <mesh
              name="Cylinder"
              geometry={nodes.Cylinder.geometry}
              material={materials.Solids}
              castShadow
              receiveShadow
              position={[776.13, 302, 207.75]}
            />
          </group>
          <group name="HILLS" position={[-61.66, 76.04, -800]}>
            <mesh
              name="Rectangle 6"
              geometry={nodes['Rectangle 6'].geometry}
              material={materials.Mountains}
              castShadow
              receiveShadow
              position={[1230.7, 36.1, -600]}
              scale={[1.9, 1, 1]}
            />
            <mesh
              name="Rectangle 5"
              geometry={nodes['Rectangle 5'].geometry}
              material={materials.Mountains}
              castShadow
              receiveShadow
              position={[-66.27, -102.26, 0]}
              scale={[2.84, 1, 1]}
            />
            <mesh
              name="Rectangle 4"
              geometry={nodes['Rectangle 4'].geometry}
              material={materials.Mountains}
              castShadow
              receiveShadow
              position={[-496.16, 15.96, -600]}
              scale={[1.38, 1, 1]}
            />
            <mesh
              name="Rectangle 3"
              geometry={nodes['Rectangle 3'].geometry}
              material={materials.Mountains}
              castShadow
              receiveShadow
              position={[630.55, 267.51, -800]}
              scale={[1.38, 1, 1]}
            />
            <mesh
              name="Rectangle 2"
              geometry={nodes['Rectangle 2'].geometry}
              material={materials.Mountains}
              castShadow
              receiveShadow
              position={[-1079.14, -6.04, -1000]}
              scale={[2.23, 1, 1]}
            />
            <mesh
              name="Rectangle"
              geometry={nodes.Rectangle.geometry}
              material={materials.Mountains}
              castShadow
              receiveShadow
              position={[257.08, -6.04, -300]}
              scale={[1.4, 1, 1]}
            />
          </group>
          <group name="CLOUDS" position={[18.2, 189.16, 196.53]}>
            <group name="cloud 5" position={[1274.44, 10.16, 403.47]} scale={0.48}>
              <mesh
                name="Shape 0"
                geometry={nodes['Shape 0'].geometry}
                material={materials.Cloud}
                castShadow
                receiveShadow
                position={[-228.35, 127.28, -20]}
              />
            </group>
            <group name="cloud 4" position={[-1098.69, 224.9, 3.47]} scale={0.59}>
              <mesh
                name="Shape 01"
                geometry={nodes['Shape 01'].geometry}
                material={materials.Cloud}
                castShadow
                receiveShadow
                position={[-228.35, 127.28, -20]}
              />
            </group>
            <group name="cloud 3" position={[662.19, 373.19, 203.47]} scale={0.66}>
              <mesh
                name="Shape 02"
                geometry={nodes['Shape 02'].geometry}
                material={materials.Cloud}
                castShadow
                receiveShadow
                position={[-228.35, 127.28, -20]}
              />
            </group>
            <group name="cloud 2" position={[287.55, -372.3, -396.53]} scale={0.83}>
              <mesh
                name="Shape 03"
                geometry={nodes['Shape 03'].geometry}
                material={materials.Cloud}
                castShadow
                receiveShadow
                position={[-228.35, 127.28, -20]}
              />
            </group>
            <group name="cloud" position={[-559.52, -53.81, 203.47]}>
              <mesh
                name="Shape 04"
                geometry={nodes['Shape 04'].geometry}
                material={materials.Cloud}
                castShadow
                receiveShadow
                position={[-228.35, 127.28, -20]}
              />
            </group>
          </group>
          <group name="Sparkles" position={[-21.65, 200, -1000]}>
            <group name="sparkle 12" position={[-127.71, 460.24, 0]} scale={0.5}>
              <mesh
                name="Shape"
                geometry={nodes.Shape.geometry}
                material={materials.Moon}
                castShadow
                receiveShadow
                position={[-32, 32, 0]}
              />
            </group>
            <group name="sparkle 11" position={[-833.24, 160.79, 0]} scale={0.5}>
              <mesh
                name="Shape1"
                geometry={nodes.Shape1.geometry}
                material={materials.Moon}
                castShadow
                receiveShadow
                position={[-32, 32, 0]}
              />
            </group>
            <group name="sparkle 10" position={[61.28, 64.34, 0]} scale={0.5}>
              <mesh
                name="Shape2"
                geometry={nodes.Shape2.geometry}
                material={materials.Moon}
                castShadow
                receiveShadow
                position={[-32, 32, 0]}
              />
            </group>
            <group name="sparkle 9" position={[990.75, 197.7, 0]} scale={0.5}>
              <mesh
                name="Shape3"
                geometry={nodes.Shape3.geometry}
                material={materials.Moon}
                castShadow
                receiveShadow
                position={[-32, 32, 0]}
              />
            </group>
            <group name="sparkle 8" position={[1464.01, -241.7, 0]}>
              <mesh
                name="Shape4"
                geometry={nodes.Shape4.geometry}
                material={materials.Moon}
                castShadow
                receiveShadow
                position={[-32, 32, 0]}
              />
            </group>
            <group name="sparkle 7" position={[-1026.87, -246.81, 0]}>
              <mesh
                name="Shape5"
                geometry={nodes.Shape5.geometry}
                material={materials.Moon}
                castShadow
                receiveShadow
                position={[-32, 32, 0]}
              />
            </group>
            <group name="sparkle 6" position={[1182.36, 612.77, 0]} scale={1.5}>
              <mesh
                name="Shape6"
                geometry={nodes.Shape6.geometry}
                material={materials.Moon}
                castShadow
                receiveShadow
                position={[-32, 32, 0]}
              />
            </group>
            <group name="sparkle 5" position={[-1196.02, 332.89, 0]} scale={1.5}>
              <mesh
                name="Shape7"
                geometry={nodes.Shape7.geometry}
                material={materials.Moon}
                castShadow
                receiveShadow
                position={[-32, 32, 0]}
              />
            </group>
            <mesh
              name="Shape 2"
              geometry={nodes['Shape 2'].geometry}
              material={materials.Moon}
              castShadow
              receiveShadow
              position={[-363.11, 241.86, 0]}
              scale={[0.75, 0.75, 1.5]}
            />
            <mesh
              name="Shape 3"
              geometry={nodes['Shape 3'].geometry}
              material={materials.Moon}
              castShadow
              receiveShadow
              position={[232.18, 675.3, 0]}
              scale={[0.75, 0.75, 1.5]}
            />
            <mesh
              name="Shape8"
              geometry={nodes.Shape8.geometry}
              material={materials.Moon}
              castShadow
              receiveShadow
              position={[-676.95, 586, 0]}
              scale={[0.75, 0.75, 1.5]}
            />
            <group name="sparkle 3" position={[899.2, -449.52, 0]}>
              <mesh
                name="Shape9"
                geometry={nodes.Shape9.geometry}
                material={materials.Moon}
                castShadow
                receiveShadow
                position={[-32, 32, 0]}
              />
            </group>
            <group name="sparkle 2" position={[-562.22, -268.82, 0]} scale={0.75}>
              <mesh
                name="Shape10"
                geometry={nodes.Shape10.geometry}
                material={materials.Moon}
                castShadow
                receiveShadow
                position={[-32, 32, 0]}
              />
            </group>
            <group name="sparkle" position={[347.6, 242.88, 0]} scale={1.5}>
              <mesh
                name="Shape11"
                geometry={nodes.Shape11.geometry}
                material={materials.Moon}
                castShadow
                receiveShadow
                position={[-32, 32, 0]}
              />
            </group>
          </group>
          <mesh
            name="MOON"
            geometry={nodes.MOON.geometry}
            material={nodes.MOON.material}
            rotation={[0, -Math.PI / 9, 0]}
          />
          <mesh
            name="bg glow"
            geometry={nodes['bg glow'].geometry}
            material={materials['bg glow Material']}
            castShadow
            receiveShadow
            position={[0, -405, 0]}
            rotation={[-1.4, 0, 0]}
            scale={1}
          />
          <OrthographicCamera
            name="Camera"
            makeDefault={true}
            zoom={0.65}
            far={100000}
            near={-100000}
            position={[0, 0, 1000]}
          />
          <directionalLight
            name="Directional Light"
            intensity={0.7}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-1000}
            shadow-camera-right={1000}
            shadow-camera-top={1000}
            shadow-camera-bottom={-1000}
            position={[200, 300, 300]}
          />
          <OrthographicCamera name="1" makeDefault={false} far={10000} near={-50000} />
          <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
        </scene>
      </group>
    </>
  )
}

// Componente principal que envuelve la escena en un Canvas
const SplineScene = ({ scrollY = 0, heroHeight = 0 }) => {
  // Calculate opacity and background transition based on scroll position
  const transitionPoint = heroHeight * 0.3 // Start transition at 30% of scroll through hero
  const transitionLength = heroHeight * 0.3 // Complete transition over 30% of hero height
  
  // Calculate scene opacity (fade out as scroll increases)
  const sceneOpacity = Math.max(0, 1 - Math.max(0, (scrollY - transitionPoint) / transitionLength))
  
  // State para el manejo de carga
  const [isLoading, setIsLoading] = useState(true)
  
  useEffect(() => {
    // Simular tiempo de carga para que se cargue correctamente el modelo
    const timer = setTimeout(() => {
      setIsLoading(false)
    }, 1000)
    
    return () => clearTimeout(timer)
  }, [])
  
  return (
    <div 
      className="absolute inset-0 z-0"
      style={{ 
        opacity: sceneOpacity,
        transition: 'opacity 0.2s ease-out',
      }}
    >
      {isLoading ? (
        <div className="flex items-center justify-center h-full bg-[#573372]">
          <div className="w-16 h-16 border-t-4 border-[#DADFFE] rounded-full animate-spin"></div>
        </div>
      ) : (
        <Suspense fallback={
          <div className="flex items-center justify-center h-full bg-[#573372]">
            <div className="w-16 h-16 border-t-4 border-[#DADFFE] rounded-full animate-spin"></div>
          </div>
        }>
          <Canvas
            dpr={[1, 2]}
            camera={{ position: [0, 0, 1000], far: 100000, near: -100000 }}
            style={{ background: '#573372' }}
            shadows
          >
            <Scene scrollY={scrollY} heroHeight={heroHeight} />
          </Canvas>
        </Suspense>
      )}
    </div>
  )
}

export default SplineScene;
